name: Run Lint

on:
    push:
        branches: [main]
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        env:
          SKIP: no-commit-to-branch
        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v4
              with:
                version: "0.5.7"
                enable-cache: true

            - name: Set up Python
              run: uv python install

            - name: Install the project
              run: uv sync --all-extras --dev

            - name: Run Lint (pre-commit)
              uses: pre-commit/action@v3.0.1
              with:
                extra_args: --all-files
